export const IMAGE_KEYPOINT_HOTKEYS = [
  { keys: 'A / D', action: 'Previous / next frame' },
  { keys: 'P', action: 'Select pitch' },
  { keys: '0 / `', action: 'Select KP0' },
  { keys: '1–8', action: 'Select keypoint' },
  { keys: 'Click', action: 'Place selected point' },
  { keys: '↑ ↓ ← →', action: 'Nudge marked point 0.25px' },
  { keys: 'Ctrl + arrows', action: 'Nudge 1px' },
  { keys: 'Shift + arrows', action: 'Nudge 5px' },
  { keys: 'Ctrl + Shift + arrows', action: 'Nudge 10px' },
  { keys: 'Delete', action: 'Clear selected point' },
  { keys: 'Ctrl + S', action: 'Save draft' },
  { keys: 'Ctrl + Z', action: 'Undo last change' },
  { keys: 'Ctrl + ` / 0–8', action: 'Copy same KP from previous frame' },
];
