const EVENT_TYPES = [
  'Pass',
  'Pass Received',
  'Recovery',
  'Tackle',
  'Interception',
  'Interception 2',
  'Ball Out of Play',
  'Clearance',
  'Take on',
  'Take on End',
  'Substitution',
  'Block',
  'Aerial Duel',
  'Shot',
  'Save',
  'Foul',
  'Goal',
  'Highlight Start',
  'Highlight End',
  'Referee',
  'Invalid',
];

module.exports = { EVENT_TYPES };
